PACKAGE_NAME="hid-nintendo-switch2"
PACKAGE_VERSION="__VERSION__"

BUILT_MODULE_NAME[0]="hid-nintendo"
BUILT_MODULE_LOCATION[0]="drivers/hid"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hid"

BUILT_MODULE_NAME[1]="nintendo-switch2-usb"
BUILT_MODULE_LOCATION[1]="drivers/input/joystick"
DEST_MODULE_LOCATION[1]="/kernel/drivers/input/joystick"

BUILT_MODULE_NAME[2]="nintendo-switch2-ble"
BUILT_MODULE_LOCATION[2]="drivers/input/joystick"
DEST_MODULE_LOCATION[2]="/kernel/drivers/input/joystick"

MAKE[0]="make KVERSION=$kernelver"
CLEAN="make clean KVERSION=$kernelver"
AUTOINSTALL="yes"
